# Generated by Django 5.0.4 on 2024-05-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0011_employee_address_employee_address1_employee_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='from_date_6',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='govt_service_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_salary_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pay_grade_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='position_title_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status_of_appointment_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='to_date_6',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
