# Generated by Django 5.0.4 on 2024-05-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0013_rename_elementary_education_employee_college_attend_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='highest_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='period_of_attendance_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='period_of_attendance_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='scholarship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='year_graduated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
