# Generated by Django 5.0.4 on 2024-05-18 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0014_employee_highest_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='highest_level',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='period_of_attendance_from',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='period_of_attendance_to',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='scholarship',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='year_graduated',
        ),
    ]
