# Generated by Django 5.0.4 on 2024-05-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0015_remove_employee_highest_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='children10_fullname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='children11_fullname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='children12_fullname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='children8_fullname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='children9_fullname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth10',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth11',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth12',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth8',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth9',
        ),
    ]
