# Generated by Django 5.0.4 on 2024-05-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0018_employee_full_name_employee_full_name1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='full_name1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='full_name2',
            new_name='address_2',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='tel_no1',
            new_name='full_name_1',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='tel_no2',
            new_name='full_name_2',
        ),
        migrations.AddField(
            model_name='employee',
            name='tel_no_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tel_no_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
