# Generated by Django 5.0.4 on 2024-05-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0019_rename_full_name1_employee_address_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='tel_no_1',
            new_name='tel_no1',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='tel_no_2',
            new_name='tel_no2',
        ),
    ]
