# Generated by Django 5.0.4 on 2024-05-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0022_employee_address_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_place_issued',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gov_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
