from django.db import models
from django.contrib.auth.models import User
from datetime import time
# Create your models here.



class Employee(models.Model):
    user = models.OneToOneField(User, null=True, blank=True,unique=True, on_delete=models.CASCADE)
    profile_pic = models.ImageField(default="Default_pfp.jpg", null=True, blank=True)
    employee_id = models.CharField(max_length=20,unique=True)
    surname = models.CharField(max_length=100)
    first_name = models.CharField(max_length=100)
    middle_name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(blank=True, null=True)
    employment_status = models.CharField(max_length=100, null=True, blank=True)
    name_ext = models.CharField(max_length=10, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    place_of_birth = models.CharField(max_length=100, blank=True, null=True)
    sex = models.CharField(max_length=10, blank=True, null=True)
    civil_status = models.CharField(max_length=20, blank=True, null=True)
    height_m = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    weight_kg = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    blood_type = models.CharField(max_length=10, blank=True, null=True)
    gsis_no = models.CharField(max_length=20, blank=True, null=True)
    pagibig_no = models.CharField(max_length=20, blank=True, null=True)
    philhealth_no = models.CharField(max_length=20, blank=True, null=True)
    sss_no = models.CharField(max_length=20, blank=True, null=True)
    tin_no = models.CharField(max_length=20, blank=True, null=True)
    agency_em = models.CharField(max_length=100, blank=True, null=True)
    citizenship = models.CharField(max_length=50, blank=True, null=True)
    residential_house_no = models.CharField(max_length=10, blank=True, null=True)
    residential_street = models.CharField(max_length=100, blank=True, null=True)
    residential_subd = models.CharField(max_length=100, blank=True, null=True)
    residential_brgy = models.CharField(max_length=100, blank=True, null=True)
    residential_city = models.CharField(max_length=100, blank=True, null=True)
    residential_province = models.CharField(max_length=100, blank=True, null=True)
    residential_zipcode = models.CharField(max_length=10, blank=True, null=True)
    permanent_house_no = models.CharField(max_length=10, blank=True, null=True)
    permanent_street = models.CharField(max_length=100, blank=True, null=True)
    permanent_subd = models.CharField(max_length=100, blank=True, null=True)
    permanent_brgy = models.CharField(max_length=100, blank=True, null=True)
    permanent_city = models.CharField(max_length=100, blank=True, null=True)
    permanent_province = models.CharField(max_length=100, blank=True, null=True)
    permanent_zipcode = models.CharField(max_length=10, blank=True, null=True)
    telephone = models.CharField(max_length=20, blank=True, null=True)
    mobile_number = models.CharField(max_length=20, blank=True, null=True)
    spouse_surname = models.CharField(max_length=100, blank=True, null=True)
    spouse_first_name = models.CharField(max_length=100, blank=True, null=True)
    spouse_middle_name = models.CharField(max_length=100, blank=True, null=True)
    spouse_name_ext = models.CharField(max_length=10, blank=True, null=True)
    spouse_occupation = models.CharField(max_length=100, blank=True, null=True)
    spouse_employer = models.CharField(max_length=100, blank=True, null=True)
    spouse_business_address = models.CharField(max_length=200, blank=True, null=True)
    spouse_telephone = models.CharField(max_length=20, blank=True, null=True)

    elementary_school = models.CharField(max_length=200, blank=True, null=True)  
    elementary_basic_edu = models.CharField(max_length=200, blank=True, null=True)
    elementary_attend_from = models.CharField(max_length=20, blank=True, null=True)
    elementary_attend_to = models.CharField(max_length=20, blank=True, null=True)
    elementary_unit_earn = models.CharField(max_length=20, blank=True, null=True)
    elementary_yr_grad = models.CharField(max_length=20, blank=True, null=True)
    elementary_honor_received = models.CharField(max_length=20, blank=True, null=True)

    secondary_school = models.CharField(max_length=200, blank=True, null=True)
    secondary_basic_edu = models.CharField(max_length=200, blank=True, null=True)
    secondary_attend_from = models.CharField(max_length=20, blank=True, null=True)
    secondary_attend_to = models.CharField(max_length=200, blank=True, null=True)
    secondary_unit_earn = models.CharField(max_length=200, blank=True, null=True)
    secondary_yr_grad = models.CharField(max_length=200, blank=True, null=True)
    secondary_honor_received = models.CharField(max_length=200, blank=True, null=True)

    vocational_school= models.CharField(max_length=200, blank=True, null=True) 
    vocational_basic_edu= models.CharField(max_length=200, blank=True, null=True)  
    vocational_attend_from = models.CharField(max_length=20, blank=True, null=True)
    vocational_attend_to = models.CharField(max_length=200, blank=True, null=True)
    vocational_unit_earn = models.CharField(max_length=200, blank=True, null=True)
    vocational_yr_grad = models.CharField(max_length=200, blank=True, null=True)
    vocational_honor_received  = models.CharField(max_length=200, blank=True, null=True)

    college_school = models.CharField(max_length=200, blank=True, null=True)
    college_basic_edu= models.CharField(max_length=200, blank=True, null=True)
    college_attend_from = models.CharField(max_length=20, blank=True, null=True)
    college_attend_to = models.CharField(max_length=200, blank=True, null=True)
    college_unit_earn = models.CharField(max_length=200, blank=True, null=True)
    college_yr_grad = models.CharField(max_length=200, blank=True, null=True)
    college_honor_received = models.CharField(max_length=200, blank=True, null=True)

    graduate_studies = models.CharField(max_length=200, blank=True, null=True)
    graduate_basic_edu= models.CharField(max_length=200, blank=True, null=True)
    graduate_attend_from = models.CharField(max_length=20, blank=True, null=True)
    graduate_attend_to = models.CharField(max_length=200, blank=True, null=True)
    graduate_unit_earn = models.CharField(max_length=200, blank=True, null=True)
    graduate_yr_grad = models.CharField(max_length=200, blank=True, null=True)
    graduate_honor_received = models.CharField(max_length=200, blank=True, null=True)
    
    father_surname = models.CharField(max_length=100, blank=True, null=True)     
    father_first_name = models.CharField(max_length=100, blank=True, null=True)
    father_middle_name = models.CharField(max_length=100, blank=True, null=True)
    father_name_ext = models.CharField(max_length=10, blank=True, null=True)
    mother_surname = models.CharField(max_length=100, blank=True, null=True)
    mother_first_name = models.CharField(max_length=100, blank=True, null=True)
    mother_middle_name = models.CharField(max_length=100, blank=True, null=True)
    employment_status = models.CharField(max_length=100, blank=True, null=True)
    
    children1_fullname = models.CharField(max_length=100, blank=True, null=True)  
    date_of_birth1 = models.DateField(blank=True, null=True)
    children2_fullname = models.CharField(max_length=100, blank=True, null=True)
    date_of_birth2 = models.DateField(blank=True, null=True)
    children3_fullname = models.CharField(max_length=100, blank=True, null=True)
    date_of_birth3 = models.DateField(blank=True, null=True)
    children4_fullname = models.CharField(max_length=100, blank=True, null=True)
    date_of_birth4 = models.DateField(blank=True, null=True)
    children5_fullname = models.CharField(max_length=100, blank=True, null=True)
    date_of_birth5 = models.DateField(blank=True, null=True)
    children6_fullname = models.CharField(max_length=100, blank=True, null=True)
    date_of_birth6 = models.DateField(blank=True, null=True)
    children7_fullname = models.CharField(max_length=100, blank=True, null=True)
    date_of_birth7 = models.DateField(blank=True, null=True)
    children8_fullname = models.CharField(max_length=100, blank=True, null=True)
    date_of_birth8 = models.DateField(blank=True, null=True)
    children9_fullname = models.CharField(max_length=100, blank=True, null=True)
    date_of_birth9 = models.DateField(blank=True, null=True)
    children10_fullname = models.CharField(max_length=100, blank=True, null=True)
    date_of_birth10 = models.DateField(blank=True, null=True)
    children11_fullname = models.CharField(max_length=100, blank=True, null=True)
    date_of_birth11 = models.DateField(blank=True, null=True)
    children12_fullname = models.CharField(max_length=100, blank=True, null=True)
    date_of_birth12 = models.DateField(blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null= True)

    licensure = models.CharField(max_length=100, blank=True, null=True)
    rating = models.CharField(max_length=100, blank=True, null=True)
    date = models.DateField(max_length=100, blank=True, null=True)
    place = models.CharField(max_length=100, blank=True, null=True)
    number = models.CharField(max_length=100, blank=True, null=True)
    validity = models.CharField(max_length=100, blank=True, null=True)
    licensure_1 = models.CharField(max_length=100, blank=True, null=True)
    rating_1 = models.CharField(max_length=100, blank=True, null=True)
    date_1 = models.DateField(max_length=100, blank=True, null=True)
    place_1 = models.CharField(max_length=100, blank=True, null=True)
    number_1 = models.CharField(max_length=100, blank=True, null=True)
    validity_1 = models.CharField(max_length=100, blank=True, null=True)
    licensure_2 = models.CharField(max_length=100, blank=True, null=True)
    rating_2 = models.CharField(max_length=100, blank=True, null=True)
    date_2 = models.DateField(max_length=100, blank=True, null=True)
    place_2 = models.CharField(max_length=100, blank=True, null=True)
    number_2 = models.CharField(max_length=100, blank=True, null=True)
    validity_2 = models.CharField(max_length=100, blank=True, null=True)
    licensure_3 = models.CharField(max_length=100, blank=True, null=True)
    rating_3 = models.CharField(max_length=100, blank=True, null=True)
    date_3 = models.DateField(max_length=100, blank=True, null=True)
    place_3 = models.CharField(max_length=100, blank=True, null=True)
    number_3 = models.CharField(max_length=100, blank=True, null=True)
    validity_3 = models.CharField(max_length=100, blank=True, null=True)
    licensure_4 = models.CharField(max_length=100, blank=True, null=True)
    rating_4 = models.CharField(max_length=100, blank=True, null=True)
    date_4 = models.DateField(max_length=100, blank=True, null=True)
    place_4 = models.CharField(max_length=100, blank=True, null=True)
    number_4 = models.CharField(max_length=100, blank=True, null=True)
    validity_4 = models.CharField(max_length=100, blank=True, null=True)
    licensure_5 = models.CharField(max_length=100, blank=True, null=True)
    rating_5 = models.CharField(max_length=100, blank=True, null=True)
    date_5 = models.DateField(max_length=100, blank=True, null=True)
    place_5 = models.CharField(max_length=100, blank=True, null=True)
    number_5 = models.CharField(max_length=100, blank=True, null=True)
    validity_5 = models.CharField(max_length=100, blank=True, null=True)     
    licensure_6 = models.CharField(max_length=100, blank=True, null=True)
    rating_6 = models.CharField(max_length=100, blank=True, null=True)
    date_6 = models.DateField(max_length=100, blank=True, null=True)
    place_6 = models.CharField(max_length=100, blank=True, null=True)
    number_6 = models.CharField(max_length=100, blank=True, null=True)
    validity_6 = models.CharField(max_length=100, blank=True, null=True) 
    from_date = models.DateField(max_length=100, blank=True, null=True)
    to_date = models.DateField(max_length=100, blank=True, null=True)
    position_title = models.CharField(max_length=100, blank=True, null=True)
    department = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary = models.CharField(max_length=100, blank=True, null=True)
    pay_grade = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment = models.CharField(max_length=100, blank=True, null=True)
    govt_service = models.CharField(max_length=100, blank=True, null=True)
    from_date_1 = models.DateField(max_length=100, blank=True, null=True)
    to_date_1 = models.DateField(max_length=100, blank=True, null=True)
    position_title_1 = models.CharField(max_length=100, blank=True, null=True)
    department_1 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary_1 = models.CharField(max_length=100, blank=True, null=True)
    pay_grade_1 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment_1 = models.CharField(max_length=100, blank=True, null=True)
    govt_service_1 = models.CharField(max_length=100, blank=True, null=True)
    from_date_2 = models.DateField(max_length=100, blank=True, null=True)
    to_date_2 = models.DateField(max_length=100, blank=True, null=True)
    position_title_2 = models.CharField(max_length=100, blank=True, null=True)
    department_2 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary_2 = models.CharField(max_length=100, blank=True, null=True)
    pay_grade_2 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment_2 = models.CharField(max_length=100, blank=True, null=True)
    govt_service_2 = models.CharField(max_length=100, blank=True, null=True)
    from_date_3 = models.DateField(max_length=100, blank=True, null=True)
    to_date_3 = models.DateField(max_length=100, blank=True, null=True)
    position_title_3 = models.CharField(max_length=100, blank=True, null=True)
    department_3 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary_3 = models.CharField(max_length=100, blank=True, null=True)
    pay_grade_3 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment_3 = models.CharField(max_length=100, blank=True, null=True)
    govt_service_3 = models.CharField(max_length=100, blank=True, null=True)
    from_date_4 = models.DateField(max_length=100, blank=True, null=True)
    to_date_4 = models.DateField(max_length=100, blank=True, null=True)
    position_title_4 = models.CharField(max_length=100, blank=True, null=True)
    department_4 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary_4 = models.CharField(max_length=100, blank=True, null=True)
    pay_grade_4 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment_4 = models.CharField(max_length=100, blank=True, null=True)
    govt_service_4 = models.CharField(max_length=100, blank=True, null=True)
    from_date_5 = models.DateField(max_length=100, blank=True, null=True)
    to_date_5 = models.DateField(max_length=100, blank=True, null=True)
    position_title_5 = models.CharField(max_length=100, blank=True, null=True)
    department_5 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary_5 = models.CharField(max_length=100, blank=True, null=True)
    pay_grade_5 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment_5 = models.CharField(max_length=100, blank=True, null=True)
    govt_service_5 = models.CharField(max_length=100, blank=True, null=True)
    from_date_6 = models.DateField(max_length=100, blank=True, null=True)
    to_date_6 = models.DateField(max_length=100, blank=True, null=True)
    position_title_6 = models.CharField(max_length=100, blank=True, null=True)
    department_6 = models.CharField(max_length=100, blank=True, null=True)
    monthly_salary_6 = models.CharField(max_length=100, blank=True, null=True)
    pay_grade_6 = models.CharField(max_length=100, blank=True, null=True)
    status_of_appointment_6 = models.CharField(max_length=100, blank=True, null=True)
    govt_service_6 = models.CharField(max_length=100, blank=True, null=True)

    # VI. Voluntary Work or Involvement in Civic / Non-Government / People / Voluntary Organizations
    organization_name = models.CharField(max_length=100, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    state = models.CharField(max_length=100, blank=True, null=True)
    zipcode = models.CharField(max_length=20, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)
    inclusive_dates_from = models.CharField(max_length=100, blank=True, null=True)
    inclusive_dates_to = models.CharField(max_length=100, blank=True, null=True)
    number_of_hours = models.CharField(max_length=100, blank=True, null=True)
    nature_of_work = models.CharField(max_length=100, blank=True, null=True)

    # VII. Learning and Development (L&D) Interventions/Training Programs Attended
    learning_development = models.CharField(max_length=100, blank=True, null=True)
    ld_inclusive_date_from = models.CharField(max_length=20, blank=True, null=True)
    ld_inclusive_date_to = models.CharField(max_length=20, blank=True, null=True)
    ld_number_of_hours = models.CharField(max_length=100, blank=True, null=True)
    type_of_ld = models.CharField(max_length=100, blank=True, null=True)
    conducted_sponsored = models.CharField(max_length=100, blank=True, null=True)

    # VIII. Other Information
    special_skills = models.CharField(max_length=100, blank=True, null=True)
    non_academic_distinctions = models.CharField(max_length=100, blank=True, null=True)
    membership_associations = models.CharField(max_length=100, blank=True, null=True)

    # VI. Voluntary Work or Involvement in Civic / Non-Government / People / Voluntary Organizations
    organization_name1 = models.CharField(max_length=100, blank=True, null=True)
    address1 = models.CharField(max_length=100, blank=True, null=True)
    city1 = models.CharField(max_length=100, blank=True, null=True)
    state1 = models.CharField(max_length=100, blank=True, null=True)
    zipcode1 = models.CharField(max_length=20, blank=True, null=True)
    country1 = models.CharField(max_length=100, blank=True, null=True)
    inclusive_dates_from1 = models.CharField(max_length=100, blank=True, null=True)
    inclusive_dates_to1 = models.CharField(max_length=100, blank=True, null=True)
    number_of_hours1 = models.CharField(max_length=100, blank=True, null=True)
    nature_of_work1 = models.CharField(max_length=100, blank=True, null=True)

    # VII. Learning and Development (L&D) Interventions/Training Programs Attended
    learning_development1 = models.CharField(max_length=100, blank=True, null=True)
    ld_inclusive_date_from1 = models.CharField(max_length=20, blank=True, null=True)
    ld_inclusive_date_to1 = models.CharField(max_length=20, blank=True, null=True)
    ld_number_of_hours1 = models.CharField(max_length=100, blank=True, null=True)
    type_of_ld1 = models.CharField(max_length=100, blank=True, null=True)
    conducted_sponsored1 = models.CharField(max_length=100, blank=True, null=True)

    # VIII. Other Information
    special_skills1 = models.CharField(max_length=100, blank=True, null=True)
    non_academic_distinction1 = models.CharField(max_length=100, blank=True, null=True)
    membership_associations1 = models.CharField(max_length=100, blank=True, null=True)

    # VI. Voluntary Work or Involvement in Civic / Non-Government / People / Voluntary Organizations
    organization_name2 = models.CharField(max_length=100, blank=True, null=True)
    address2  = models.CharField(max_length=100, blank=True, null=True)
    city2  = models.CharField(max_length=100, blank=True, null=True)
    state2  = models.CharField(max_length=100, blank=True, null=True)
    zipcode2  = models.CharField(max_length=20, blank=True, null=True)
    country2  = models.CharField(max_length=100, blank=True, null=True)
    inclusive_dates_from2  = models.CharField(max_length=100, blank=True, null=True)
    inclusive_dates_to2  = models.CharField(max_length=100, blank=True, null=True)
    number_of_hours2  = models.CharField(max_length=100, blank=True, null=True)
    nature_of_work2  = models.CharField(max_length=100, blank=True, null=True)

    # VII. Learning and Development (L&D) Interventions/Training Programs Attended
    learning_development2  = models.CharField(max_length=100, blank=True, null=True)
    ld_inclusive_date_from2  = models.CharField(max_length=20, blank=True, null=True)
    ld_inclusive_date_to2  = models.CharField(max_length=20, blank=True, null=True)
    ld_number_of_hours2  = models.CharField(max_length=100, blank=True, null=True)
    type_of_ld2  = models.CharField(max_length=100, blank=True, null=True)
    conducted_sponsored2  = models.CharField(max_length=100, blank=True, null=True)

    # VIII. Other Information
    special_skills2  = models.CharField(max_length=100, blank=True, null=True)
    non_academic_distinctions2  = models.CharField(max_length=100, blank=True, null=True)
    membership_associations2  = models.CharField(max_length=100, blank=True, null=True)

    # VI. Voluntary Work or Involvement in Civic / Non-Government / People / Voluntary Organizations
    organization_name3 = models.CharField(max_length=100, blank=True, null=True)
    address3 = models.CharField(max_length=100, blank=True, null=True)
    city3 = models.CharField(max_length=100, blank=True, null=True)
    state3 = models.CharField(max_length=100, blank=True, null=True)
    zipcode3 = models.CharField(max_length=20, blank=True, null=True)
    country3 = models.CharField(max_length=100, blank=True, null=True)
    inclusive_dates_from3 = models.CharField(max_length=100, blank=True, null=True)
    inclusive_dates_to3 = models.CharField(max_length=100, blank=True, null=True)
    number_of_hours3 = models.CharField(max_length=100, blank=True, null=True)
    nature_of_work3 = models.CharField(max_length=100, blank=True, null=True)

    # VII. Learning and Development (L&D) Interventions/Training Programs Attended
    learning_development3 = models.CharField(max_length=100, blank=True, null=True)
    ld_inclusive_date_from3 = models.CharField(max_length=20, blank=True, null=True)
    ld_inclusive_date_to3 = models.CharField(max_length=20, blank=True, null=True)
    ld_number_of_hours3 = models.CharField(max_length=100, blank=True, null=True)
    type_of_ld3 = models.CharField(max_length=100, blank=True, null=True)
    conducted_sponsored3 = models.CharField(max_length=100, blank=True, null=True)

    # VIII. Other Information
    special_skills3 = models.CharField(max_length=100, blank=True, null=True)
    non_academic_distinctions3 = models.CharField(max_length=100, blank=True, null=True)
    membership_associations3 = models.CharField(max_length=100, blank=True, null=True)
    
    # VI. Voluntary Work or Involvement in Civic / Non-Government / People / Voluntary Organizations
    organization_name4 = models.CharField(max_length=100, blank=True, null=True)
    address4 = models.CharField(max_length=100, blank=True, null=True)
    city4 = models.CharField(max_length=100, blank=True, null=True)
    state4 = models.CharField(max_length=100, blank=True, null=True)
    zipcode4 = models.CharField(max_length=20, blank=True, null=True)
    country4 = models.CharField(max_length=100, blank=True, null=True)
    inclusive_dates_from4 = models.CharField(max_length=100, blank=True, null=True)
    inclusive_dates_to4 = models.CharField(max_length=100, blank=True, null=True)
    number_of_hours4 = models.CharField(max_length=100, blank=True, null=True)
    nature_of_work4 = models.CharField(max_length=100, blank=True, null=True)

    # VII. Learning and Development (L&D) Interventions/Training Programs Attended
    learning_development4 = models.CharField(max_length=100, blank=True, null=True)
    ld_inclusive_date_from4 = models.CharField(max_length=20, blank=True, null=True)
    ld_inclusive_date_to4 = models.CharField(max_length=20, blank=True, null=True)
    ld_number_of_hours4 = models.CharField(max_length=100, blank=True, null=True)
    type_of_ld4 = models.CharField(max_length=100, blank=True, null=True)
    conducted_sponsored4 = models.CharField(max_length=100, blank=True, null=True)

    # VIII. Other Information
    special_skills4 = models.CharField(max_length=100, blank=True, null=True)
    non_academic_distinctions4 = models.CharField(max_length=100, blank=True, null=True)
    membership_associations4 = models.CharField(max_length=100, blank=True, null=True)

    # VI. Voluntary Work or Involvement in Civic / Non-Government / People / Voluntary Organizations
    organization_name5 = models.CharField(max_length=100, blank=True, null=True)
    address5 = models.CharField(max_length=100, blank=True, null=True)
    city5 = models.CharField(max_length=100, blank=True, null=True)
    state5 = models.CharField(max_length=100, blank=True, null=True)
    zipcode5 = models.CharField(max_length=20, blank=True, null=True)
    country5 = models.CharField(max_length=100, blank=True, null=True)
    inclusive_dates_from5 = models.CharField(max_length=100, blank=True, null=True)
    inclusive_dates_to5 = models.CharField(max_length=100, blank=True, null=True)
    number_of_hours5 = models.CharField(max_length=100, blank=True, null=True)
    nature_of_work5 = models.CharField(max_length=100, blank=True, null=True)

    # VII. Learning and Development (L&D) Interventions/Training Programs Attended
    learning_development5 = models.CharField(max_length=100, blank=True, null=True)
    ld_inclusive_date_from5 = models.CharField(max_length=20, blank=True, null=True)
    ld_inclusive_date_to5 = models.CharField(max_length=20, blank=True, null=True)
    ld_number_of_hours5 = models.CharField(max_length=100, blank=True, null=True)
    type_of_ld5 = models.CharField(max_length=100, blank=True, null=True)
    conducted_sponsored5 = models.CharField(max_length=100, blank=True, null=True)

    # VIII. Other Information
    special_skills5 = models.CharField(max_length=100, blank=True, null=True)
    non_academic_distinctions_5 = models.CharField(max_length=100, blank=True, null=True)
    membership_associations5 = models.CharField(max_length=100, blank=True, null=True)

    # VI. Voluntary Work or Involvement in Civic / Non-Government / People / Voluntary Organizations
    organization_name6 = models.CharField(max_length=100, blank=True, null=True)
    address6 = models.CharField(max_length=100, blank=True, null=True)
    city6 = models.CharField(max_length=100, blank=True, null=True)
    state6 = models.CharField(max_length=100, blank=True, null=True)
    zipcode6 = models.CharField(max_length=20, blank=True, null=True)
    country6 = models.CharField(max_length=100, blank=True, null=True)
    inclusive_dates_from6 = models.CharField(max_length=100, blank=True, null=True)
    inclusive_dates_to6 = models.CharField(max_length=100, blank=True, null=True)
    number_of_hours6 = models.CharField(max_length=100, blank=True, null=True)
    nature_of_work6 = models.CharField(max_length=100, blank=True, null=True)

    # VII. Learning and Development (L&D) Interventions/Training Programs Attended
    learning_development6 = models.CharField(max_length=100, blank=True, null=True)
    ld_inclusive_date_from6 = models.CharField(max_length=20, blank=True, null=True)
    ld_inclusive_date_to6 = models.CharField(max_length=20, blank=True, null=True)
    ld_number_of_hours6 = models.CharField(max_length=100, blank=True, null=True)
    type_of_ld6 = models.CharField(max_length=100, blank=True, null=True)
    conducted_sponsored6 = models.CharField(max_length=100, blank=True, null=True)
    
    # VIII. Other Information
    special_skills6 = models.CharField(max_length=100, blank=True, null=True)
    non_academic_distinctions_6 = models.CharField(max_length=100, blank=True, null=True)
    membership_associations6 = models.CharField(max_length=100, blank=True, null=True)

    #References
    full_name = models.CharField(max_length=200, blank=True, null=True) 
    address_1 = models.CharField(max_length=200, blank=True, null=True) 
    tel_no = models.CharField(max_length=200, blank=True, null=True)
    full_name_1 = models.CharField(max_length=200, blank=True, null=True) 
    address_2 = models.CharField(max_length=200, blank=True, null=True) 
    tel_no1 = models.CharField(max_length=200, blank=True, null=True)  
    full_name_2 = models.CharField(max_length=200, blank=True, null=True) 
    address_3 = models.CharField(max_length=200, blank=True, null=True) 
    tel_no2 = models.CharField(max_length=200, blank=True, null=True) 
    gov_id = models.CharField(max_length=200, blank=True, null=True)
    id_no = models.CharField(max_length=200, blank=True, null=True)
    date_place_issued = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return f"{self.employee_id} - {self.first_name} {self.surname}"


class OfficialTime(models.Model):
    employee_id = models.CharField(max_length=20)
    day = models.CharField(max_length = 10)
    semester_id = models.CharField(max_length = 10, null= True, blank = True)
    official_office_in = models.TimeField(default='00:00:00', null=True, blank=True)
    official_office_out = models.TimeField(default='00:00:00', null=True, blank=True)
    official_honorarium_time_in = models.TimeField(default='00:00:00', null=True, blank=True)
    official_honorarium_time_out = models.TimeField(default='00:00:00', null=True, blank=True)
    official_servicecredit_time_in = models.TimeField(default='00:00:00', null=True, blank=True)
    official_servicecredit_time_out = models.TimeField(default='00:00:00', null=True, blank=True)
    official_overtime_time_in = models.TimeField(default='00:00:00', null=True, blank=True)
    official_overtime_time_out = models.TimeField(default='00:00:00', null=True, blank=True)


class AttendanceRecord(models.Model):
    employee_id = models.CharField(max_length=100, null=True, blank=True)
    date = models.DateField(null=True, blank=True)
    time_in = models.TimeField(default='00:00:00', null=True, blank=True)
    break_in = models.TimeField(default='00:00:00', null=True, blank=True)
    break_out = models.TimeField(default='00:00:00', null=True, blank=True)
    time_out = models.TimeField(default='00:00:00', null=True, blank=True)
    surplusHour_time_in = models.TimeField(default='00:00:00', null=True, blank=True)
    surplusHour_time_out = models.TimeField(default='00:00:00', null=True, blank=True)

    def __str__(self):
        return f"{self.employee_id} - {self.date}" if self.date else self.employee_id


class EditLogs(models.Model):
    attendance_record = models.ForeignKey(AttendanceRecord, on_delete=models.CASCADE)
    edited_by = models.ForeignKey(User, on_delete=models.CASCADE)
    logged_data = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)